# Generated by Django 5.0.2 on 2024-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres y apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_contacto', models.IntegerField(choices=[(0, 'Peticiones'), (1, 'Quejas'), (2, 'Reclamos'), (3, 'Sugerencia')], verbose_name='Razón del contacto')),
                ('notificacion', models.BooleanField(default=False, verbose_name='Recibir respuesta al correo')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
        ),
    ]
