# Generated by Django 5.0.2 on 2024-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
